/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.distribuidos.interface_usuarios.views;

import co.edu.unicauca.distribuidos.interface_usuarios.models.ClienteDTO;
import co.edu.unicauca.distribuidos.interface_usuarios.services.UsuarioServices;
import javax.swing.JOptionPane;


public class IngresarCliente extends javax.swing.JFrame {

    /**
     * Creates new form IngresarCliente
     */
    public IngresarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldContrasenia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegstrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 130, 38, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Teléfono:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 210, 50, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setText("Login:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 280, 33, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 350, 62, 16);

        jTextFieldNombre.setBackground(new java.awt.Color(247, 247, 247));
        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(60, 90, 176, 40);

        jTextFieldApellido.setBackground(new java.awt.Color(247, 247, 247));
        jTextFieldApellido.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(250, 90, 176, 40);

        jTextFieldCorreo.setBackground(new java.awt.Color(247, 247, 247));
        jTextFieldCorreo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldCorreo.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextFieldCorreo);
        jTextFieldCorreo.setBounds(60, 150, 176, 40);

        jTextFieldTelefono.setBackground(new java.awt.Color(247, 247, 247));
        jTextFieldTelefono.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldTelefono.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextFieldTelefono);
        jTextFieldTelefono.setBounds(60, 230, 176, 40);

        jTextFieldLogin.setBackground(new java.awt.Color(247, 247, 247));
        jTextFieldLogin.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldLogin.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextFieldLogin);
        jTextFieldLogin.setBounds(60, 300, 176, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 60, 47, 16);

        jTextFieldContrasenia.setBackground(new java.awt.Color(247, 247, 247));
        jTextFieldContrasenia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldContrasenia.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextFieldContrasenia);
        jTextFieldContrasenia.setBounds(60, 370, 176, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 60, 47, 16);

        jButtonRegstrar.setBackground(new java.awt.Color(0, 153, 255));
        jButtonRegstrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegstrar.setText("REGISTRAR");
        jButtonRegstrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegstrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegstrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegstrar);
        jButtonRegstrar.setBounds(310, 410, 105, 37);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("Nuevo Cliente");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 10, 154, 32);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegstrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegstrarActionPerformed
        try {
            UsuarioServices objAdminServices = new UsuarioServices();
            ClienteDTO objCliente = new ClienteDTO(jTextFieldNombre.getText(), jTextFieldApellido.getText(), jTextFieldCorreo.getText(),jTextFieldTelefono.getText(),jTextFieldLogin.getText(), jTextFieldContrasenia.getText());
            ClienteDTO objClienteRegistrado = objAdminServices.registrarCliente(objCliente);
            JOptionPane.showMessageDialog(null, "CLIENTE REGISTRADO CON EXITO!!!");
            Login ventanaLogin = new Login();
            this.setVisible(false);
            ventanaLogin.setVisible(true);
        } catch (Exception NullException) {
            JOptionPane.showMessageDialog(null, "CLIENTE NO REGISTRADO!!!",
                    "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            Login ventanaLogin = new Login();
            this.setVisible(false);
            ventanaLogin.setVisible(true);
        }
    }//GEN-LAST:event_jButtonRegstrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegstrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldContrasenia;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
